language: node_js
node_js:
- stable
  
before_install:
- openssl aes-256-cbc -K $encrypted_de7331c916d1_key -iv $encrypted_de7331c916d1_iv
  -in deploy_private.enc -out deploy_private -d

env:
  global:
  - ENCRYPTION_LABEL: "de7331c916d1"

scripts: bash ./travis-deploy.sh
